# All keys are overridden by CLI args and optional, unless otherwise
# stated.

# Repo map is a map from a repo name to various args. If the given --name
# matches an entry here, its values will be used, unless overridden by
# the CLI.
[[repo-map]]
# Mandatory repo name.
name = 'nixos/nixpkgs'

# Map of names to branch filters.
branches = [ '*master', '*unstable*' ]

# Domain to use.
domain = 'github.com'

# https or ssh.
protocol = 'https'

[[repo-map]]
name = 'org/repo'
branches = [
  'origin/master',
  'origin/staging'
]

# Miscellaneous options.
[logging]

# Enables logging colors. Can be 'on' or 'off', defaults to 'on'.
log-color = 'on'

# Enables logging. Can be 'debug' or 'info'.
log-level = 'debug'

# Miscellaneous options.
[miscellaneous]

# Always performs a clean clone. Not recommended for performance. Can be
# 'on' or 'off'.
clean = 'off'
